name: Generate Manifest

on:
  workflow_dispatch:

  push:
    branches:
      - master
    paths:
      - '**.lua'
      - '**/help/*.txt'

jobs:
  manifest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Generate Manifest
      run: |-
        cd ./src
        bash $GITHUB_WORKSPACE/.bin/manifest.sh

    - name: Commit Changes
      run: |-
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add $GITHUB_WORKSPACE/src/manifest.json
        git commit -m "Generate new manifest"
        git push
